### ISSUE TITLE
RCV Prototype Metaissue

### ISSUE THREAD

**Issue by JDziurlaj** [HiltonRoscoe/CDFPrototype#2]
- [x] Documentation on principle of operation
- [x] Documentation of EML subset (RCV features only)
- [x] Review static PDF Boilerplate
